namespace BankTransactionConciliationAPI.Models.AutoGenerated
{
    // NOTE: Generated code may require at least .NET Framework 4.5 or .NET Core/Standard 2.0.
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class OFX
    {

        private OFXSIGNONMSGSRSV1 sIGNONMSGSRSV1Field;

        private OFXBANKMSGSRSV1 bANKMSGSRSV1Field;

        /// <remarks/>
        public OFXSIGNONMSGSRSV1 SIGNONMSGSRSV1
        {
            get
            {
                return this.sIGNONMSGSRSV1Field;
            }
            set
            {
                this.sIGNONMSGSRSV1Field = value;
            }
        }

        /// <remarks/>
        public OFXBANKMSGSRSV1 BANKMSGSRSV1
        {
            get
            {
                return this.bANKMSGSRSV1Field;
            }
            set
            {
                this.bANKMSGSRSV1Field = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class OFXSIGNONMSGSRSV1
    {

        private OFXSIGNONMSGSRSV1SONRS sONRSField;

        /// <remarks/>
        public OFXSIGNONMSGSRSV1SONRS SONRS
        {
            get
            {
                return this.sONRSField;
            }
            set
            {
                this.sONRSField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class OFXSIGNONMSGSRSV1SONRS
    {

        private OFXSIGNONMSGSRSV1SONRSSTATUS sTATUSField;

        private string dTSERVERField;

        private string lANGUAGEField;

        /// <remarks/>
        public OFXSIGNONMSGSRSV1SONRSSTATUS STATUS
        {
            get
            {
                return this.sTATUSField;
            }
            set
            {
                this.sTATUSField = value;
            }
        }

        /// <remarks/>
        public string DTSERVER
        {
            get
            {
                return this.dTSERVERField;
            }
            set
            {
                this.dTSERVERField = value;
            }
        }

        /// <remarks/>
        public string LANGUAGE
        {
            get
            {
                return this.lANGUAGEField;
            }
            set
            {
                this.lANGUAGEField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class OFXSIGNONMSGSRSV1SONRSSTATUS
    {

        private byte cODEField;

        private string sEVERITYField;

        /// <remarks/>
        public byte CODE
        {
            get
            {
                return this.cODEField;
            }
            set
            {
                this.cODEField = value;
            }
        }

        /// <remarks/>
        public string SEVERITY
        {
            get
            {
                return this.sEVERITYField;
            }
            set
            {
                this.sEVERITYField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class OFXBANKMSGSRSV1
    {

        private OFXBANKMSGSRSV1STMTTRNRS sTMTTRNRSField;

        /// <remarks/>
        public OFXBANKMSGSRSV1STMTTRNRS STMTTRNRS
        {
            get
            {
                return this.sTMTTRNRSField;
            }
            set
            {
                this.sTMTTRNRSField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class OFXBANKMSGSRSV1STMTTRNRS
    {

        private ushort tRNUIDField;

        private OFXBANKMSGSRSV1STMTTRNRSSTATUS sTATUSField;

        private OFXBANKMSGSRSV1STMTTRNRSSTMTRS sTMTRSField;

        /// <remarks/>
        public ushort TRNUID
        {
            get
            {
                return this.tRNUIDField;
            }
            set
            {
                this.tRNUIDField = value;
            }
        }

        /// <remarks/>
        public OFXBANKMSGSRSV1STMTTRNRSSTATUS STATUS
        {
            get
            {
                return this.sTATUSField;
            }
            set
            {
                this.sTATUSField = value;
            }
        }

        /// <remarks/>
        public OFXBANKMSGSRSV1STMTTRNRSSTMTRS STMTRS
        {
            get
            {
                return this.sTMTRSField;
            }
            set
            {
                this.sTMTRSField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class OFXBANKMSGSRSV1STMTTRNRSSTATUS
    {

        private byte cODEField;

        private string sEVERITYField;

        /// <remarks/>
        public byte CODE
        {
            get
            {
                return this.cODEField;
            }
            set
            {
                this.cODEField = value;
            }
        }

        /// <remarks/>
        public string SEVERITY
        {
            get
            {
                return this.sEVERITYField;
            }
            set
            {
                this.sEVERITYField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class OFXBANKMSGSRSV1STMTTRNRSSTMTRS
    {

        private string cURDEFField;

        private OFXBANKMSGSRSV1STMTTRNRSSTMTRSBANKACCTFROM bANKACCTFROMField;

        private OFXBANKMSGSRSV1STMTTRNRSSTMTRSBANKTRANLIST bANKTRANLISTField;

        private OFXBANKMSGSRSV1STMTTRNRSSTMTRSLEDGERBAL lEDGERBALField;

        /// <remarks/>
        public string CURDEF
        {
            get
            {
                return this.cURDEFField;
            }
            set
            {
                this.cURDEFField = value;
            }
        }

        /// <remarks/>
        public OFXBANKMSGSRSV1STMTTRNRSSTMTRSBANKACCTFROM BANKACCTFROM
        {
            get
            {
                return this.bANKACCTFROMField;
            }
            set
            {
                this.bANKACCTFROMField = value;
            }
        }

        /// <remarks/>
        public OFXBANKMSGSRSV1STMTTRNRSSTMTRSBANKTRANLIST BANKTRANLIST
        {
            get
            {
                return this.bANKTRANLISTField;
            }
            set
            {
                this.bANKTRANLISTField = value;
            }
        }

        /// <remarks/>
        public OFXBANKMSGSRSV1STMTTRNRSSTMTRSLEDGERBAL LEDGERBAL
        {
            get
            {
                return this.lEDGERBALField;
            }
            set
            {
                this.lEDGERBALField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class OFXBANKMSGSRSV1STMTTRNRSSTMTRSBANKACCTFROM
    {

        private ushort bANKIDField;

        private ulong aCCTIDField;

        private string aCCTTYPEField;

        /// <remarks/>
        public ushort BANKID
        {
            get
            {
                return this.bANKIDField;
            }
            set
            {
                this.bANKIDField = value;
            }
        }

        /// <remarks/>
        public ulong ACCTID
        {
            get
            {
                return this.aCCTIDField;
            }
            set
            {
                this.aCCTIDField = value;
            }
        }

        /// <remarks/>
        public string ACCTTYPE
        {
            get
            {
                return this.aCCTTYPEField;
            }
            set
            {
                this.aCCTTYPEField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class OFXBANKMSGSRSV1STMTTRNRSSTMTRSBANKTRANLIST
    {

        private string dTSTARTField;

        private string dTENDField;

        private OFXBANKMSGSRSV1STMTTRNRSSTMTRSBANKTRANLISTSTMTTRN[] sTMTTRNField;

        /// <remarks/>
        public string DTSTART
        {
            get
            {
                return this.dTSTARTField;
            }
            set
            {
                this.dTSTARTField = value;
            }
        }

        /// <remarks/>
        public string DTEND
        {
            get
            {
                return this.dTENDField;
            }
            set
            {
                this.dTENDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("STMTTRN")]
        public OFXBANKMSGSRSV1STMTTRNRSSTMTRSBANKTRANLISTSTMTTRN[] STMTTRN
        {
            get
            {
                return this.sTMTTRNField;
            }
            set
            {
                this.sTMTTRNField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class OFXBANKMSGSRSV1STMTTRNRSSTMTRSBANKTRANLISTSTMTTRN
    {

        private string tRNTYPEField;

        private string dTPOSTEDField;

        private decimal tRNAMTField;

        private string mEMOField;

        /// <remarks/>
        public string TRNTYPE
        {
            get
            {
                return this.tRNTYPEField;
            }
            set
            {
                this.tRNTYPEField = value;
            }
        }

        /// <remarks/>
        public string DTPOSTED
        {
            get
            {
                return this.dTPOSTEDField;
            }
            set
            {
                this.dTPOSTEDField = value;
            }
        }

        /// <remarks/>
        public decimal TRNAMT
        {
            get
            {
                return this.tRNAMTField;
            }
            set
            {
                this.tRNAMTField = value;
            }
        }

        /// <remarks/>
        public string MEMO
        {
            get
            {
                return this.mEMOField;
            }
            set
            {
                this.mEMOField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class OFXBANKMSGSRSV1STMTTRNRSSTMTRSLEDGERBAL
    {

        private decimal bALAMTField;

        private string dTASOFField;

        /// <remarks/>
        public decimal BALAMT
        {
            get
            {
                return this.bALAMTField;
            }
            set
            {
                this.bALAMTField = value;
            }
        }

        /// <remarks/>
        public string DTASOF
        {
            get
            {
                return this.dTASOFField;
            }
            set
            {
                this.dTASOFField = value;
            }
        }
    }
}
